AWSTemplateFormatVersion: '2010-09-09'
Description: Main Template for Account 2
Parameters:
  VpcCidr:
    Description: "CIDR block for the VPC"
    Type: String
    # Default: "10.0.0.0/16"
  PublicSubnetCidr:
    Description: "CIDR block for the public subnet"
    Type: String
    # Deflt: "10.0.1.0/24"
  BucketName:
    Description: "CIDR block for the public subnet"
    Type: String
    # Default: "10.0.1.0/24"
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/akin-ses-files-us-east-2/vpc-template.yaml  #../modules/vpc/vpc-template.yaml
      Parameters:
        VpcCidr: !Ref VpcCidr
        PublicSubnetCidr: !Ref PublicSubnetCidr

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/akin-ses-files-us-east-2/s3-template.yaml  #../modules/s3/s3-template.yaml
      Parameters:
        BucketName: !Ref BucketName


#it is liu8393l
#oaeiohjpoiajepoadadadiiuhiuhiuhjqoejadaheihapoe[apojudhiaoh]