AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Template

Parameters:
  BucketName:
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
