AWSTemplateFormatVersion: '2010-09-09'
Description: Main Template for Account 1

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/vpc/vpc-template.yaml
      Parameters:
        VpcCidr: !Ref VpcCidr
        PublicSubnetCidr: !Ref PublicSubnetCidr

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../modules/s3/s3-template.yaml
      Parameters:
        BucketName: !Ref BucketName

#it is lufjk3983984kkjl
####ojaoiherwldeojeoakndklna;doiaujopdijuao9hu98e]]]adaajpeoij