name: Deploy CloudFormation

on:
  push:
    branches:
      - main
    paths:
      - account-1/**
      - account-2/**

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      account_1_changed: ${{ steps.set-env.outputs.account_1_changed }}
      account_2_changed: ${{ steps.set-env.outputs.account_2_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for accurate git diff

      - name: Set up Environment
        id: set-env
        run: |
          echo "Checking for modified files..."
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            echo "account_1_changed=true" >> $GITHUB_ENV
            echo "account_2_changed=true" >> $GITHUB_ENV
            echo "::set-output name=account_1_changed::true"
            echo "::set-output name=account_2_changed::true"
          else
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} > files_changed.txt
            if grep -q '^account-1/' files_changed.txt; then
              echo "account_1_changed=true" >> $GITHUB_ENV
              echo "::set-output name=account_1_changed::true"
            else
              echo "account_1_changed=false" >> $GITHUB_ENV
              echo "::set-output name=account_1_changed::false"
            fi
            if grep -q '^account-2/' files_changed.txt; then
              echo "account_2_changed=true" >> $GITHUB_ENV
              echo "::set-output name=account_2_changed::true"
            else
              echo "account_2_changed=false" >> $GITHUB_ENV
              echo "::set-output name=account_2_changed::false"
            fi
          fi
        shell: bash

  deploy-account-1:
    runs-on: ubuntu-latest
    needs: determine-changes
    if: needs.determine-changes.outputs.account_1_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up AWS CLI for Account 1
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACCOUNT_1 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACCOUNT_1 }}
          aws-region: us-east-1

      - name: Upload CloudFormation template to S3
        run: |
          aws s3 cp ./modules/s3/s3-template.yaml s3://akin-ses-files/s3-template.yaml
          aws s3 cp ./modules/vpc/vpc-template.yaml s3://akin-ses-files/vpc-template.yaml

      - name: Deploy CloudFormation stack for Account 1
        run: |
          PARAMS=$(jq -r '.Parameters | to_entries | map("\(.key)=\(.value|tostring)") | join(" ")' account-1/parameters.json)
          echo "Deploying stack for Account 1 with parameters: ${PARAMS}"
          aws cloudformation deploy \
            --template-file account-1/main-template.yaml \
            --stack-name my-stack-account-1 \
            --parameter-overrides ${PARAMS}
        shell: bash

  deploy-account-2:
    runs-on: ubuntu-latest
    needs: determine-changes
    if: needs.determine-changes.outputs.account_2_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up AWS CLI for Account 2
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACCOUNT_2 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACCOUNT_2 }}
          aws-region: us-east-2

      - name: Deploy CloudFormation stack for Account 2
        run: |
          if [ -f account-2/parameters.json ]; then
            PARAMS=$(jq -r '.Parameters | to_entries | map("\(.key)=\(.value|tostring)") | join(" ")' account-2/parameters.json)
          else
            PARAMS=""
          fi
          echo "Deploying stack for Account 2 with parameters: ${PARAMS}"
          aws cloudformation deploy \
            --template-file account-2/main-template.yaml \
            --stack-name my-stack-account-2 \
            --parameter-overrides ${PARAMS}
        shell: bash
