name: Deploy CloudFormation

on:
  push:
    branches:
      - main
    paths:
      - account-1/**
      - account-2/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Environment
        run: |
          echo "Checking for modified files..."
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            echo "first_push=true" >> $GITHUB_ENV
            echo "account_1_changed=true" >> $GITHUB_ENV
            echo "account_2_changed=true" >> $GITHUB_ENV
          else
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} > files_changed.txt
            if grep -q '^account-1/' files_changed.txt; then
              echo "account_1_changed=true" >> $GITHUB_ENV
            else
              echo "account_1_changed=false" >> $GITHUB_ENV
            fi
            if grep -q '^account-2/' files_changed.txt; then
              echo "account_2_changed=true" >> $GITHUB_ENV
            else
              echo "account_2_changed=false" >> $GITHUB_ENV
            fi
          fi

  deploy-account-1:
    runs-on: ubuntu-latest
    needs: deploy
    if: env.account_1_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up AWS CLI for Account 1
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACCOUNT_1 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACCOUNT_1 }}
          aws-region: us-east-1

      - name: Deploy CloudFormation stack for Account 1
        run: |
          PARAMS=$(jq -r '.Parameters | to_entries | map("\(.key)=\(.value|tostring)") | join(" ")' account-1/parameters.json)
          echo "Deploying stack for Account 1 with parameters: ${PARAMS}"
          aws cloudformation deploy \
            --template-file account-1/main-template.yaml \
            --stack-name my-stack-account-1 \
            --parameter-overrides ${PARAMS}
        shell: bash

  deploy-account-2:
    runs-on: ubuntu-latest
    needs: deploy
    if: env.account_2_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up AWS CLI for Account 2
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACCOUNT_2 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACCOUNT_2 }}
          aws-region: us-east-2

      - name: Deploy CloudFormation stack for Account 2
        run: |
          PARAMS=$(jq -r '.Parameters | to_entries | map("\(.key)=\(.value|tostring)") | join(" ")' account-2/parameters.json)
          echo "Deploying stack for Account 2 with parameters: ${PARAMS}"
          aws cloudformation deploy \
            --template-file account-2/main-template.yaml \
            --stack-name my-stack-account-2 \
            --parameter-overrides ${PARAMS}
        shell: bash
