name: Deploy CloudFormation

on:
  push:
    branches:
      - main
    paths:
      - account-1/**
      - account-2/**
      - modules/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Fetch enough history to compare changes

    - name: Determine modified files
      id: changes
      run: |
        echo "Checking for modified files..."
        if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
          echo "First push detected, deploying to both accounts."
          echo "changed-files=ALL" >> $GITHUB_ENV
        else
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files:"
          echo "$CHANGED_FILES"
          echo "changed-files=${CHANGED_FILES}" >> $GITHUB_ENV
        fi

    # - name: Debug - Show changed files output
    #   run: echo "Changed files: ${{ env.changed-files }}"

    - name: Read parameters for Account 1
      if: ${{ env.changed-files == 'ALL' || contains(env.changed-files, 'account-1/') }}
      id: read_params_1
      run: |
        PARAMS=$(jq -r '.Parameters | to_entries | map("\(.key)=\(.value|tostring)") | join(" ")' account-1/parameters.json)
        echo "params=${PARAMS}" >> $GITHUB_ENV

    - name: Set up AWS CLI for Account 1
      if: ${{ env.changed-files == 'ALL' || contains(env.changed-files, 'account-1/') }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACCOUNT_1 }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACCOUNT_1 }}
        aws-region: us-east-1

    - name: Deploy CloudFormation stack for Account 1
      if: ${{ env.changed-files == 'ALL' || contains(env.changed-files, 'account-1/') }}
      run: |
        aws cloudformation deploy \
          --template-file account-1/main-template.yaml \
          --stack-name my-stack-account-1 \
          --parameter-overrides ${{ env.params }}

    - name: Read parameters for Account 2
      if: ${{ env.changed-files == 'ALL' || contains(env.changed-files, 'account-2/') }}
      id: read_params_2
      run: |
        PARAMS=$(jq -r '.Parameters | to_entries | map("\(.key)=\(.value|tostring)") | join(" ")' account-2/parameters.json)
        echo "params=${PARAMS}" >> $GITHUB_ENV

    - name: Set up AWS CLI for Account 2
      if: ${{ env.changed-files == 'ALL' || contains(env.changed-files, 'account-2/') }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACCOUNT_2 }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACCOUNT_2 }}
        aws-region: us-east-2

    - name: Deploy CloudFormation stack for Account 2
      if: ${{ env.changed-files == 'ALL' || contains(env.changed-files, 'account-2/') }}
      run: |
        aws cloudformation deploy \
          --template-file account-2/main-template.yaml \
          --stack-name my-stack-account-2 \
          --parameter-overrides ${{ env.params }}
